# Netlify 빌드 설정
[build]
  # 빌드 결과물이 생성되는 폴더를 지정합니다.
  # Create React App의 기본값은 'build' 입니다.
  publish = "build"
  # 빌드 명령어
  command = "npm run build"

# SPA 리다이렉트 규칙
# 모든 경로 요청을 메인 index.html로 보내줍니다.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200